### ISSUE TITLE
Got floating point exception and segfault when running mcpat

### ISSUE THREAD

**Issue by jonathan-alvaro** [Ayymoose/gem5-mcpat-parser#1]
When running parsefix, I encountered an error that says error code 0010000. I traced it and found out that this resulted from the system.cpu  being called system.core0 instead. After fixing it, the parsefix script seems to work and I managed to run mcpat. But, when I ran mcpat according to the execution line in the compute script, mcpat returns a floating point exception. Can you help me with this?

**Comment by Ayymoose** [comment]
Sorry for my late reply, I wasn't aware anyone was using my repository for anything. I haven't used McPAT for a few years so I've forgotten most of everything. So you need the stats.txt that uses the DerivO3CPU (detailed?) otherwise it throws an FP exception?
